#!/bin/bash 

set -eo pipefail


chain=$1
ref_fasta_seq=$2



# INPUT DEL
###########
# chr1    2523792 SV1     ACGCCCCCTCCCCTGCTGTGCTGGCACCCCCTCCCCTGCCGCGCTGATGCCCCCTCCCCTGATGCACTGGCGCCCCCTCCCCTGCCATGCTGACGCCCCCTCCCCTGCCGTGCTGGCGCCCCCTCCCCTGCCGCGCTGACGCCCCCTCCCCTGCCGCGCTGACGCCCCCTCCCCTGCCGCGCTGATGCCCCCTCCCCTGCCGTGCTGG   A       .       .       VARTYPE=SV;SVTYPE=DEL;SVLEN=-207;ID=chr1-2592354-DEL-207;LEAD_SAMPLE=HG00731;TIG_REGION=cluster8_000020F:1171593-1171593;TIG_STRAND=+   GT      1|1
# SVEND = 2523792 + 207 = 2523999
# ../scripts/extractDNAseq.tcl chr1 2523792 2523999 $hg19_ref_fasta_seq


# INPUT INS
###########
# chr1    2524045 SV2     A       ATGCCCCCTCCCCTGAGGCACTGGTGCCCCCCTCCCCTGCAGCGCTGATGCCCCCCCTCCCCTGCCATGCTGACGCCCCCTCCCCTGATGCACTGG        .       .       VARTYPE=SV;SVTYPE=INS;SVLEN=95;ID=chr1-2592607-INS-95;LEAD_SAMPLE=HG03486;TIG_REGION=cluster1_000040F:1119007-1119101;TIG_STRAND=+ GT      0|1
# ../scripts/extractDNAseq.tcl chr1 2524045 2524045 $hg19_ref_fasta_seq => A

rm -f ./output/output_hg38.*

python3 $LIFTOVERSV/bin/liftoverSV.py -i ./input/input_hg19.vcf -o ./output/output_hg38.vcf -c $chain -r $ref_fasta_seq


# OUTPUT DEL
############
# chr1    2592353 SV1     ACGCCCCCTCCCCTGCTGTGCTGGCACCCCCTCCCCTGCCGCGCTGATGCCCCCTCCCCTGATGCACTGGCGCCCCCTCCCCTGCCATGCTGACGCCCCCTCCCCTGCCGTGCTGGCGCCCCCTCCCCTGCCGCGCTGACGCCCCCTCCCCTGCCGCGCTGACGCCCCCTCCCCTGCCGCGCTGATGCCCCCTCCCCTGCCGTGCTGG   A       .       .       VARTYPE=SV;SVTYPE=DEL;SVLEN=-207;ID=chr1-2592354-DEL-207;LEAD_SAMPLE=HG00731;TIG_REGION=cluster8_000020F:1171593-1171593;TIG_STRAND=+   GT      1|1
# SVEND = 2592353 + 207 = 2592560
# ../scripts/extractDNAseq.tcl chr1 2592353 2592560 $hg38_ref_fasta_seq

# OUTPUT INS
############
# chr1    2592606 SV2     A       ATGCCCCCTCCCCTGAGGCACTGGTGCCCCCCTCCCCTGCAGCGCTGATGCCCCCCCTCCCCTGCCATGCTGACGCCCCCTCCCCTGATGCACTGG        .       .       VARTYPE=SV;SVTYPE=INS;SVLEN=95;ID=chr1-2592607-INS-95;LEAD_SAMPLE=HG03486;TIG_REGION=cluster1_000040F:1119007-1119101;TIG_STRAND=+ GT      0|1
# ../scripts/extractDNAseq.tcl chr1 2592606 2592606 $hg38_ref_fasta_seq => A


# Manual check of the input/output DEL:
# => DEL hg19/hg38 sequence comparison
#######################################
# hg19 ("REF from VCF" then "sequence from extractDNAseq.tcl")
# ACGCCCCCTCCCCTGCTGTGCTGGCACCCCCTCCCCTGCCGCGCTGATGCCCCCTCCCCTGATGCACTGGCGCCCCCTCCCCTGCCATGCTGACGCCCCCTCCCCTGCCGTGCTGGCGCCCCCTCCCCTGCCGCGCTGACGCCCCCTCCCCTGCCGCGCTGACGCCCCCTCCCCTGCCGCGCTGATGCCCCCTCCCCTGCCGTGCTGG
# ACGCCCCCTCCCCTGCTGTGCTGGCACCCCCTCCCCTGCCGCGCTGATGCCCCCTCCCCTGATGCACTGGcgccccctcccctgccatgctgacgccccctcccctgccgtgctggcgccccctcccctgccgcgctgacgccccctcccctgccgcgctgacgccccctcccctgccgcgctgatgccccctcccctgccgtgctgg
#
# hg38 ("REF from VCF" then "sequence from extractDNAseq.tcl")
# ACGCCCCCTCCCCTGCTGTGCTGGCACCCCCTCCCCTGCCGCGCTGATGCCCCCTCCCCTGATGCACTGGCGCCCCCTCCCCTGCCATGCTGACGCCCCCTCCCCTGCCGTGCTGGCGCCCCCTCCCCTGCCGCGCTGACGCCCCCTCCCCTGCCGCGCTGACGCCCCCTCCCCTGCCGCGCTGATGCCCCCTCCCCTGCCGTGCTGG
# ACGCCCCCTCCCCTGCTGTGCTGGCACCCCCTCCCCTGCCGCGCTGATGCCCCCTCCCCTGATGCACTGGCGCCCCCTCCCCTGCCATGCTGACGCCCCCTCCCCTGCCGTGCTGGCGCCCCCTCCCCTGCCGCGCTGACGCCCCCTCCCCTGCCGCGCTGACGCCCCCTCCCCTGCCGCGCTGATGCCCCCTCCCCTGCCGTGCTGG
#
# => OK



gunzip ./output/output_hg38.sort.vcf.gz
if [ -e ./validated_output/validated_output_hg38.sort.vcf.gz ]
then
	gunzip ./validated_output/validated_output_hg38.sort.vcf.gz
fi

compare=`diff ./output/output_hg38.sort.vcf validated_output/validated_output_hg38.sort.vcf || true`

gzip ./output/output_hg38.sort.vcf
gzip ./validated_output/validated_output_hg38.sort.vcf


if [ "$compare" ]
then
        echo "$compare"
        echo `basename $(pwd)`": ERROR, not the expected values"
else
        echo "ok - Finished"
fi


